# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Reus 2014"
email: "conferencias@gdgtarragona.net"
description: "GDG DevFest is a set of events all around the world"
baseurl: "/zeppelin"
url: "http://gdgtarragona.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-55386227-1"
googleAnalyticsSiteUrl: "gdgtarragona.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Tarragona"
organizerAlternateName: "Google Developer Group Tarragona"
organizerDescription: "Comunidad de Desarrolladores Google Tarragona"
organizerEmail: "conferencias@gdgtarragona.net"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.gdgtarragona.net/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, reus, Tarragona"
twitterAccount: "@GDGTarragona"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://goo.gl/7mIDvi"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Ponentes"}
 - {permalink: "/team/", text: "Equipo"}
 - {permalink: "/logistics/", text: "Como llegar"}
 - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "http://goo.gl/fISuGq", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "http://goo.gl/fISuGq", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest <typeout> 2014"
eventDate: “25 Octubre, 2014"
typeoutTextValues: '"", "Reus", "Tarragona"'
typeoutFallback: "Season"
heroButtons:
 - {link: "http://goo.gl/fISuGq", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Consigue una entrada"}

# About Block
aboutTitle: “Sobre GDG DevFest"
aboutBlock:
 - {title: "Conferencias", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lot's of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day free-style hackaton! Want some real teambuilding on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "130", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "12", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "9", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Lugar de las conferencias"
eventLocationLink: "http://www.firareus.com/"
eventStreetAddress: "firaReus, Tecnoparc"
eventAddressLocality: "Avda de Bellisens"
eventAddressLocalityRegion: "Reus"
eventPostalCode: "43203"
eventAddressCountry: "Spain"
eventStartTime: "2014-10-25T9:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "41.143097, 1.129242"
mapCenterCoordinates: "41.143097, 1.129242"
mapMobileCenterCoordinates: "41.143097, 1.129242"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "firaReus"
venueFeatures: ["firaReus, Centro de Ferias y Convenciones", "Localizado en la Ciudad de Reus en el área Tecnoparc"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest Reus"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://eepurl.com/4ZRzn"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Entrada"
  price: "0"
  priceCurrency: "€"
  ticketsNumber: "200"
  ribbon: "Free"
  buyButtonLink: "http://devfestreus.eventbrite.es"
  buyButtonText: "Buy Now"
  ticketContentList: ["Entrada general", "", ""]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-10-24T23:59"
# Footer
socialLinks:
 - {link: "https://plus.google.com/b/110881000795710392242", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGTarragona", icon: "twitter"}
 - {link: "https://facebook.com/GDGTarragona", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdgtarragona.net", text: “GDGTarragona"}
   - {link: "https://events.gdgtarragona.net", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:conferencias@gdgtarragona.net", text: “Contacto"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Últimas noticias"
blogCommentsEnabled: true
discusShortName: "DevFestReus"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Los GDG DevFest son eventos organizados por los Google Developer Groups de todo el mundo. Tienen lugar entre los meses de septiembre y noviembre centrandose principalmente en tecnologías Google.

Por primera vez, este año llega a la provincia de Tarragona el GDG DevFest Reus de la mano del GDG Tarragona. El evento tendrá lugar el sábado 25 de octubre en las instalaciones de firaReus en el Tecnoparc."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "49.056728, 3.117289"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around firaReus"
directionDetailsCards:
 - {title: "Aeropuerto", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://www.aena-aeropuertos.es/csee/Satellite/Aeropuerto-Reus/es/">airport website</a>.'}
 - {title: "Transporte púbico", information: 'Google Transit is available in Reus. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Reus Transport.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Información"
    links:
     - {link: "https://www.gdgtarragona.net", text: "GDG Tarragona"}



# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Remotte",image: "hackathon-1.png"}
 - {title: "Android Wear",image: "hackathon-0.png"}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Jueces"

# Hackathon Prizes Block
prizesTitle: "Premios"
prizes:
 - {title: "1nd Place Remotte ", image: "prize-2.png", info: "Remotte"}
 - {title: "1nd Place Reus Transport", image: "prize-1.png", info: "Premio Reus Transport"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Foyeur"
hackathonLocationLink: "http://www.firaReus.cat"
hackathonStreetAddress: "Avda. de Bellisens, 40"
hackathonAddressLocality: "Reus"
hackathonAddressLocalityRegion: "Tarragona"
hackathonPostalCode: "43204"
hackathonAddressCountry: "Spain"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-5T10:00"
hackathonDoorTime: "18:00"
hackathonEndTime: "2014-10-25T18:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "41.143097, 1.129242"
hackathonMapCenterCoordinates: "41.143097, 1.129242"
hackathonMapMobileCenterCoordinates: "41.143097, 1.129242"
